spring:
   profiles:
    active: -dev
---
server:
 port: 8093

spring:
   profiles: dev  #开发环境
   application :
     name: provider-service

# 注册中心地址
eureka:
  client:
   service-url:
    defaultZone: http://localhost:8090/eureka/
---
server:
 port: 8010

spring:
   profiles: test  #开发环境
   application :
      name: provider-service

# 注册中心地址
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8090/eureka/